config/routes.rb
TransMarket::Application.routes.draw do
  devise_for :users

  devise_for :models

  resources :categories

  resources :products
  root :to => 'categories#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name, :parent, :uid, :products
  set_primary_key :uid

  has_many :products, autosave: true
  has_many :parent_category_association, :class_name => "ParentCategory", :foreign_key => "parent_id"
  has_many :parent_categories, :through => :parent_category_association, :source => :parent_category
  has_many :child_category_association, :class_name => "ParentCategory", :foreign_key => "parent_id"
  has_many :child_categories, :through => :child_category_association, :source => :child_category

  accepts_nested_attributes_for :products, allow_destroy: true
  validate :min_info, on: :update

  def as_json(args=nil)
    puts child_categories.inspect
    {
      id: uid,
      name: name,
      children: children,
      parents: parents
    }
  end

  def parents
    parent_categories.map {|cat| cat.as_json }
  end

  def children
    child_categories.map {|cat| cat.as_json }
  end

  def products=(prods)
    #prods.each {|prod| prod['category_id'] = id}
    self.products_attributes = prods
  end

  def min_info
    #errors.add(:min_contact_info, 'min_contact_info') if products.length == 0
  end
end

app/models/model.rb
class Model < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/parent_category.rb
class ParentCategory < ActiveRecord::Base
  attr_accessible :child_id, :parent_id
  belongs_to :child_category, foreign_key: :child_id, class_name: 'Category'
  belongs_to :parent_category, foreign_key: :parent_id, class_name: 'Category'
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :description, :is_mobile, :location, :name, :price, :uid

  belongs_to :category

  #validates_presence_of :description
  validates :description, uniqueness: { scope: :name, message: 'uniqueness'}

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :phone
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all

    respond_to do |format|
      format.html { bootstrap(params) }
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new
    @categories = Category.all

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
    bootstrap(params)
  end

  # POST /categories
  # POST /categories.json
  def create
   params[:category]['products'] = [
     {name: 'first', description: 'last'},
     {name: 'first', description: 'last'}
   ]
    puts params.inspect
    @category = Category.new(params[:category])

   respond_to do |format|
     if @category.save
       format.html { redirect_to @category, notice: 'Category was successfully created.' }
       format.json { render json: @category, status: :created, location: @category }
     else
       format.html { render action: "new" }
       format.json { render json: @category.errors, status: :unprocessable_entity }
     end
   end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end

  def bootstrap(prms)
    render template: 'categories/categories_bootstrap'
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # GET /products
  # GET /products.json
  def index
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/categories/_form.html.haml
= form_for(@category) do |f|
  - if @category.errors.any?
    #error_explanation
      %h2
        = pluralize(@category.errors.count, "error")
        prohibited this category from being saved:
      %ul
        - @category.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .field
    = f.label :uid
    %br/
    = f.text_field :uid
  .field
    = f.label :parent
    %br/
    = f.text_field :parent
  .actions
    = f.submit

app/views/categories/categories_bootstrap.html.erb
<div id="categories"></div>

<script type="text/javascript">
$(function() {
 TransMarket.router = new TransMarket.Routers.CategoriesRouter({categories:  <%= @categories.to_json.html_safe -%>});
 TransMarket.categories = new TransMarket.Collections.CategoriesCollection
 TransMarket.initialize_backbone();
});
</script>

app/views/categories/edit.html.haml
%h1 Editing category
= render 'form'
= link_to 'Show', @category
|
\#{link_to 'Back', categories_path}

app/views/categories/index_old.html.haml
%h1 Listing categories
%table
  %tr
    %th Name
    %th Uid
    %th Parent
    %th
    %th
    %th
  - @categories.each do |category|
    %tr
      %td= category.name
      %td= category.uid
      %td= category.parent
      %td= link_to 'Show', category
      %td= link_to 'Edit', edit_category_path(category)
      %td= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Category', new_category_path

app/views/categories/new.html.haml
%h1 New category
= render 'form'
= link_to 'Back', categories_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TransMarket</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
 <p class="notice"><%= notice %></p>
 <p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>

app/views/products/_form.html.haml
= form_for(@product) do |f|
  - if @product.errors.any?
    #error_explanation
      %h2
        = pluralize(@product.errors.count, "error")
        prohibited this product from being saved:
      %ul
        - @product.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :uid
    %br/
    = f.text_field :uid
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .field
    = f.label :description
    %br/
    = f.text_area :description
  .field
    = f.label :price
    %br/
    = f.text_field :price
  .field
    = f.label :location
    %br/
    = f.text_field :location
  .field
    = f.label :is_mobile
    %br/
    = f.check_box :is_mobile
  .actions
    = f.submit

app/views/products/edit.html.haml
%h1 Editing product
= render 'form'
= link_to 'Show', @product
|
\#{link_to 'Back', products_path}

app/views/products/index.html.haml
%h1 Listing products 
%table
  %tr
    %th Name
    %th Uid
    %th Category
    %th description
    %th price
    %th location
    %th is_mobile
    %th
    %th
    %th
  - @products.each do |product|
    %tr
      %td= product.name
      %td= product.uid
      %td= product.category
      %td= product.description
      %td= product.price
      %td= product.location
      %td= product.is_mobile
      %td= link_to 'Show', product 
      %td= link_to 'Edit', edit_product_path(product)
      %td= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Category', new_product_path

app/views/products/new.html.haml
%h1 New category
= render 'form'
= link_to 'Back', categories_path

app/views/products/show.html.haml
%p#notice= notice
%p
  %b Name:
  = @category.name
%p
  %b Uid:
  = @category.uid
%p
  %b Parent:
  = @category.parent
= link_to 'Edit', edit_category_path(@category)
|
\#{link_to 'Back', categories_path}